"""initial migration

Revision ID: 627a744c5114
Revises: 
Create Date: 2025-07-02 15:07:14.498676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627a744c5114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=150), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customerId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('menuItems',
    sa.Column('menuItemId', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('item_category', sa.String(length=150), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('menuItemId'),
    sa.UniqueConstraint('item_category')
    )
    op.create_table('vendors',
    sa.Column('vendorId', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=150), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vendorId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('cartItems',
    sa.Column('cartItemId', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('menuItemId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['customers.customerId'], ),
    sa.ForeignKeyConstraint(['menuItemId'], ['menuItems.menuItemId'], ),
    sa.PrimaryKeyConstraint('cartItemId')
    )
    op.create_table('carts',
    sa.Column('cartId', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['customers.customerId'], ),
    sa.PrimaryKeyConstraint('cartId')
    )
    op.create_table('contactMessages',
    sa.Column('messageId', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['customers.customerId'], ),
    sa.PrimaryKeyConstraint('messageId')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.String(length=150), nullable=False),
    sa.Column('total_amount', sa.String(length=22), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['customers.customerId'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    op.create_table('reviews',
    sa.Column('reviewId', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('menuItemId', sa.Integer(), nullable=False),
    sa.Column('vendorId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['customers.customerId'], ),
    sa.ForeignKeyConstraint(['menuItemId'], ['menuItems.menuItemId'], ),
    sa.ForeignKeyConstraint(['vendorId'], ['vendors.vendorId'], ),
    sa.PrimaryKeyConstraint('reviewId')
    )
    op.create_table('deliveries',
    sa.Column('deliveryId', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('deliveryAddress', sa.String(length=255), nullable=False),
    sa.Column('deliveryStatus', sa.String(length=50), nullable=False),
    sa.Column('deliveryDate', sa.DateTime(), nullable=True),
    sa.Column('rider_name', sa.String(length=100), nullable=True),
    sa.Column('rider_phone', sa.String(length=15), nullable=True),
    sa.Column('rider_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ),
    sa.PrimaryKeyConstraint('deliveryId')
    )
    op.create_table('orderitems',
    sa.Column('orderItemId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=150), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=True),
    sa.Column('menuItemId', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['menuItemId'], ['menuItems.menuItemId'], ),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ),
    sa.PrimaryKeyConstraint('orderItemId')
    )
    op.create_table('payments',
    sa.Column('paymentId', sa.Integer(), nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('paymentMethod', sa.String(length=50), nullable=False),
    sa.Column('paymentStatus', sa.String(length=50), nullable=False),
    sa.Column('paymentDate', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ),
    sa.PrimaryKeyConstraint('paymentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('orderitems')
    op.drop_table('deliveries')
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_table('contactMessages')
    op.drop_table('carts')
    op.drop_table('cartItems')
    op.drop_table('vendors')
    op.drop_table('menuItems')
    op.drop_table('customers')
    # ### end Alembic commands ###
